{{- range .Values.applications }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: identity-cell
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }} 
      targetPort: {{ .port }} 
      protocol: TCP
  selector:
    app: {{ .name }}
{{- end }} 