# identity-cell/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # El nombre del service de tu API Gateway
            name: identity-gateway
            port:
              # El puerto del service de tu API Gateway
              number: 8080