{{/* Este bucle creará un Service para cada microservicio */}}
{{- range $name, $values := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  # El nombre del Service será el mismo que el del microservicio (ej. "auth-service")
  # Este es el nombre DNS que usarán para comunicarse.
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  # El selector es el vínculo clave: este Service enviará tráfico
  # a cualquier Pod que tenga la etiqueta "app: <nombre-del-servicio>".
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      # El puerto por el que el Service escuchará.
      port: {{ $values.port }}
      # El puerto al que se reenviará el tráfico en el Pod.
      targetPort: {{ $values.port }}
---
{{- end }}