server:
  port: 8080

spring:
  application:
    name: cell-gateway
  cloud:
    discovery:
        client:
            simple:
              instances:
                  account-service:
                  - uri: http://account-service:8081
                  auth-service:
                  - uri: http://auth-service:8082
                  authz-service:
                  - uri: http://authz-service:8083
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/identity/api/v1/accounts/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/identity/api/v1/auth/**
          filters:
            - StripPrefix=1
        - id: authz-service
          uri: lb://authz-service
          predicates:
            - Path=/identity/api/v1/authz/**
          filters:
            - StripPrefix=1

management: # Configuracion del Actuator
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics, gateway, refresh
